### ISSUE TITLE
Interchangeable fragments aimed at different readers

### ISSUE THREAD

**Issue by akhmerov** [ExecutableBookProject/myst_parser#75]
I'm teaching a course right now, and I observed again that some students need a much simpler material presentation than others. I think one way to accommodate this is having interchangeable segments of text that the readers can switch to the presentation they prefer.

Is myst markup sufficiently flexible to support this? Is this an interesting feature to implement?

**Comment by chrisjsewell** [comment]
Possibly. How would you envisage this working? The simplest way I can think of is a directive like:

````
```{interchange} simple
Here the simple version
```
```{interchange} advanced
Heres the advanced version
```
````

That created a toggle in the HTML to switch between the two.

There's already extension that do nearly this like, like [sphinx-tabs](https://github.com/djungelorm/sphinx-tabs) (although this particular extension isn't quite working in myst yet, because of #55)

**Comment by akhmerov** [comment]
Nice, didn't know about tabs. Tabs would definitely work. Your proposed syntax seems even better because it allows for a global switch: the different alternatives are labeled by their logical relation to the material.

**Comment by choldgraf** [comment]
and more generally from @chrisjsewell 's point, the question isn't "is MyST flexible enough for this", it is "is Sphinx flexible enough for this". If you can do it in Sphinx, you can do it in MyST. In this case, the answer would be "make or use a directive for this" I think

**Comment by akhmerov** [comment]
@choldgraf ah, perhaps that's my real question: what does one need to do beyond making a sphinx extension that introduces a new directive/role for it to work in a sphinx site built from myst documents?

Will it work out of the box?

**Comment by choldgraf** [comment]
If we've done our job with Myst, anything written in Myst should work the *exact* same way compared to it being written in rST. There will probably always be edge cases and such, but 95% should be the same.

**Comment by akhmerov** [comment]
Thanks for the explanation. Closing as irrelevant to this repo, might revisit when the book-related work is being done.
